### PR TITLE
Add Node.js examples

### PR DESCRIPTION
**Pull request by dbrennand**
This PR adds Node.js examples for interacting with UKCloud's ECS based Cloud Storage service.

### CODE REVIEW

**Comment by dbrennand** [comment]
Please hold off on merge. Adding more examples.

**Comment by dbrennand** [comment]
Ready for PR @cblackuk 😄

**Review by cblackuk — APPROVED** [review]
LGTM

**Review by cblackuk — APPROVED** [review]
LGTM

**Pull request merged**
